# Generated by Django 4.1 on 2022-08-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='servicio_hotel',
        ),
        migrations.AddField(
            model_name='hotel',
            name='servicio_hotel',
            field=models.ManyToManyField(blank=True, null=True, to='hotel.serviciohotel'),
        ),
    ]
