# Generated by Django 4.1 on 2022-08-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_remove_hotel_servicio_hotel_hotel_servicio_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidad',
            name='servicio_unidad',
        ),
        migrations.AddField(
            model_name='unidad',
            name='servicio_unidad',
            field=models.ManyToManyField(blank=True, null=True, to='hotel.serviciounidad'),
        ),
    ]
