# Generated by Django 4.1 on 2022-08-27 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_remove_unidad_servicio_unidad_unidad_servicio_unidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='unidad',
        ),
        migrations.AddField(
            model_name='unidad',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel'),
        ),
    ]
