# Generated by Django 4.1 on 2022-08-28 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_remove_hotel_unidad_unidad_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidad',
            name='nombre',
        ),
    ]
