# Generated by Django 4.1 on 2022-09-06 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_remove_unidad_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad',
            name='precio',
            field=models.FloatField(null=True),
        ),
    ]
