# Generated by Django 4.1 on 2022-09-06 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_unidad_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='precio_hotel',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
