# Generated by Django 4.1 on 2022-09-06 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_hotel_precio_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidad',
            name='precio',
        ),
    ]
