# Generated by Django 4.1 on 2022-09-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_remove_unidad_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='servicio_hotel',
            field=models.ManyToManyField(blank=True, to='hotel.serviciohotel'),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='servicio_unidad',
            field=models.ManyToManyField(blank=True, to='hotel.serviciounidad'),
        ),
    ]
